extends: eslint:recommended
parser: esprima
parserOptions:
  ecmaVersion: 2015
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
env:
  node: true
rules:
  brace-style: [ error, 1tbs ]
  indent: [ error, 4 ]
  keyword-spacing: error
  no-var: error
globals:
  Promise: true
overrides:
  files: [ '**/*.js' ]
  # ignore ghost and content files once unzipped and bootstrapped (local dev)
  excludedFiles: [ 'app/**/*.js', 'mycontent/**/*.js' ]
